### ISSUE TITLE
A different UI

### ISSUE THREAD

**Issue by hackintoshlover** [robdobsn/RBotFirmware#17]
Hi Rob,
Thanks for the awesome project.
So i followed all steps on your website:
https://robdobson.com/2018/09/sandbot-software-revamp/
and programmed the huzzah32, but upon accessing sandui.html i get get a website which looks different and a little confusing.
Attached is the picture of webpage being displayed:
![Screenshot_2022-11-25_02-41-43](https://user-images.githubusercontent.com/40655406/203865923-1a465e66-59aa-469f-9819-54432b295230.png)

Am i doing something wrong?
Kindly help.
Thanks.

**Comment by noedger** [comment]
Hi there HackintoshloverNope you did not do anything wrong in particular. I had the same way back when I build mine. Im just trying to think back to what the cause was. Will give it some thought and let you know during the course of the day. Think its something small ......just cant remember right now. Will go through my notes. RegardsDeonSent from my Galaxy
-------- Original message --------From: hackintoshlover ***@***.***> Date: 2022/11/24  23:40  (GMT+02:00) To: robdobsn/RBotFirmware ***@***.***> Cc: Subscribed ***@***.***> Subject: [robdobsn/RBotFirmware] A different UI (Issue #17) 
Hi Rob,
Thanks for the awesome project.
So i followed all steps on your website:
https://robdobson.com/2018/09/sandbot-software-revamp/
and programmed the huzzah32, but upon accessing sandui.html i get get a website which looks different and a little confusing.
Attached is the picture of webpage being displayed:

Am i doing something wrong?
Kindly help.
Thanks.

**Comment by hackintoshlover** [comment]
Hey thanks for the quick response.
Eagerly waiting for your reply on the UI.
Also how do i control led strip from the UI.
Thanks.

**Comment by noedger** [comment]
HiMe again. Sorry for the late respons. Busy day. For the LED light strip Im not sure that you can controle it via the app. Its controlled by a ambient sensor as far as I know. I do not use led's on my table. I did find a fork on github that said that he fixed the LED strip. In what manner Im not sure. https://github.com/DanalEstes/RBotFirmwareIts worth looking into that.This is the repo I used because I could not get Robs to work in my Visual code ide without errors. If you use Whatsapp you will get my attention much quiker for futher related questions. Im glad to help. Thinking back it was a mountain for me to climb because of the limited help available. Mat has helped me tremendously. If your patiant I'll send through whatever links to info I still have. If you can give my a detailed description of how you went about in loading the code, connecting it via wifi and accesing it through the UI I might pick up on your problem. Importantly what operating system you used as well for I know that Mac is problematic while android or windows works fine. My Whatsapp contact:RegardsDeonSent from my Galaxy
-------- Original message --------From: hackintoshlover ***@***.***> Date: 2022/11/25  08:53  (GMT+02:00) To: robdobsn/RBotFirmware ***@***.***> Cc: noedger ***@***.***>, Comment ***@***.***> Subject: Re: [robdobsn/RBotFirmware] A different UI (Issue #17) 
Hey thanks for the quick response.
Eagerly waiting for your reply on the UI.
Also how do i control led strip from the UI.
Thanks.

**Comment by hackintoshlover** [comment]
> HiMe again. Sorry for the late respons. Busy day. For the LED light strip Im not sure that you can controle it via the app. Its controlled by a ambient sensor as far as I know. I do not use led's on my table. I did find a fork on github that said that he fixed the LED strip. In what manner Im not sure. https://github.com/DanalEstes/RBotFirmwareIts worth looking into that.This is the repo I used because I could not get Robs to work in my Visual code ide without errors. If you use Whatsapp you will get my attention much quiker for futher related questions. Im glad to help. Thinking back it was a mountain for me to climb because of the limited help available. Mat has helped me tremendously. If your patiant I'll send through whatever links to info I still have. If you can give my a detailed description of how you went about in loading the code, connecting it via wifi and accesing it through the UI I might pick up on your problem. Importantly what operating system you used as well for I know that Mac is problematic while android or windows works fine. My Whatsapp contact:+27761352225RegardsDeonSent from my Galaxy -------- Original message --------From: hackintoshlover ***@***.***> Date: 2022/11/25 08:53 (GMT+02:00) To: robdobsn/RBotFirmware ***@***.***> Cc: noedger ***@***.***>, Comment ***@***.***> Subject: Re: [robdobsn/RBotFirmware] A different UI (Issue #17) Hey thanks for the quick response. Eagerly waiting for your reply on the UI. Also how do i control led strip from the UI. Thanks. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

Hi,
Thanks for the reply.
I'll check the link you have sent and get back to you on the same.
As for Rob's original code repository, the code compiles perfectly fine when used with platformio and espressif framework version 2.1.0
I am able to control led brightness using android app which can be downloaded by clicking the link below:
https://alwaystinkering.com/files/sandbot-debug-v4.apk

Upon downloading and installing enter ip address of your sand table.
The builtin webserver of the sand table <ip/sand.html> does not contain a provision for controlling the led strip.

I am just facing the UI issue as mentioned above which looks different, using the sand table via the app as of now.
Thanks.

P.S. : Kindly edit the post and delete your number i have saved it.

**Comment by noedger** [comment]
HiNot sure I fully understand your problem. The UI that your pic shows is the one that Rob de eloped with the sandbot firmware. The APK android app Ui was developed by Matt as mentioned before as a thirdparty development. They do look completely different.......thats normal. I thought that you were refering to the fact that it shows up blank without tracks. As I can recall I used the cnc Ui to load tracks. One other thing worth mentioning is the sd card. The system is very fuzzy on recognizing som memory cards. That can also give you a blank screen. Try to use the cnc UI to check and diagnose. If I miss interpret your problem feel free to give me a bump in the right direction. RegardsDeonSent from my Galaxy
-------- Original message --------From: hackintoshlover ***@***.***> Date: 2022/11/25  22:36  (GMT+02:00) To: robdobsn/RBotFirmware ***@***.***> Cc: noedger ***@***.***>, Comment ***@***.***> Subject: Re: [robdobsn/RBotFirmware] A different UI (Issue #17) 



HiMe again. Sorry for the late respons. Busy day. For the LED light strip Im not sure that you can controle it via the app. Its controlled by a ambient sensor as far as I know. I do not use led's on my table. I did find a fork on github that said that he fixed the LED strip. In what manner Im not sure. https://github.com/DanalEstes/RBotFirmwareIts worth looking into that.This is the repo I used because I could not get Robs to work in my Visual code ide without errors. If you use Whatsapp you will get my attention much quiker for futher related questions. Im glad to help. Thinking back it was a mountain for me to climb because of the limited help available. Mat has helped me tremendously. If your patiant I'll send through whatever links to info I still have. If you can give my a detailed description of how you went about in loading the code, connecting it via wifi and accesing it through the UI I might pick up on your problem. Importantly what operating system you used as well for I know that Mac is problematic while android or windows works fine. My Whatsapp contact:+27761352225RegardsDeonSent from my Galaxy -------- Original message --------From: hackintoshlover @.> Date: 2022/11/25 08:53 (GMT+02:00) To: robdobsn/RBotFirmware @.> Cc: noedger @.>, Comment @.> Subject: Re: [robdobsn/RBotFirmware] A different UI (Issue #17) Hey thanks for the quick response. Eagerly waiting for your reply on the UI. Also how do i control led strip from the UI. Thanks. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: @.***>



Hi,

Thanks for the reply.

I'll check the link you have sent and get back to you on the same.

As for Rob's original code repository, the code compiles perfectly fine when used with platformio and espressif framework version 2.1.0

I am able to control led brightness using android app which can be downloaded by clicking the link below:

https://alwaystinkering.com/files/sandbot-debug-v4.apk

Upon downloading and installing enter ip address of your sand table.

The builtin webserver of the sand table <ip/sand.html> does not contain a provision for controlling the led strip.

I am just facing the UI issue as mentioned above which looks different, using the sand table via the app as of now.

Thanks.

P.S. : Kindly edit the post and delete your number i have saved it.

**Comment by hackintoshlover** [comment]
UI has been updated.
